-- LOCAL-DEV ONLY shim.
-- On the shared BBQ Architect production DB these objects already exist (created
-- by the BBQ app), so every statement here is guarded with IF NOT EXISTS and is
-- a NO-OP on production. Locally it lays down the minimal subset of BBQ tables
-- the POS depends on, so `supabase db reset` can apply the pos_phase_* migrations
-- + seed against a fresh database.
--
-- This is NOT the source of truth for BBQ's schema (that lives in the BBQ repo).
-- It only mirrors the columns the POS reads/links to.

create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

-- Tenant root (subset of BBQ's organizations).
create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null,
  created_at timestamptz not null default now()
);

-- Membership (subset of BBQ's organization_members). pos_role + manager_pin_hash
-- are added by pos_phase_a; role/status mirror BBQ's free-text model.
create table if not exists public.organization_members (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null,
  role text not null default 'Medewerker',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

-- BBQ's org resolver. The POS adopts this exact function; it is NEVER redefined
-- on production. Guarded so we only create it locally when absent.
do $$
begin
  if not exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'current_org_id'
  ) then
    execute $fn$
      create function public.current_org_id()
      returns uuid language sql stable security definer set search_path = 'public'
      as 'select organization_id from public.organization_members where user_id = auth.uid() and status = ''active'' limit 1'
    $fn$;
  end if;
end $$;

-- Shared catalog (subset). pos_menu_items.gerecht_id -> gerechten(id). The pos_*
-- columns were added to BBQ's gerechten by an earlier (abandoned) POS attempt;
-- we mirror them so the menu linking works in local dev.
create table if not exists public.gerechten (
  id uuid primary key default gen_random_uuid(),
  naam text not null,
  beschrijving text default '',
  organization_id uuid,
  allergenen text[] default '{}',
  tags text[] default '{}',
  pos_enabled boolean default false,
  pos_categorie text default 'main',
  pos_prijs numeric,
  pos_volgorde int default 0,
  verkoopprijs numeric default 0,
  btw_tarief numeric default 9,
  foto_url text,
  actief boolean default true,
  created_at timestamptz default now()
);

-- AI usage (BBQ shape; pos_phase_c adds venue_id/prompt_version/latency_ms).
create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  organization_id uuid not null,
  user_id uuid,
  action_type text not null,
  model text,
  tokens_input int default 0,
  tokens_output int default 0,
  tokens_cache_read int default 0,
  tokens_cache_creation int default 0,
  cost_eur_cents int default 0,
  metadata jsonb default '{}',
  created_at timestamptz not null default now()
);

-- EU 1169/2011 allergen reference (subset).
create table if not exists public.allergens (
  code text primary key,
  nl_label text not null,
  eu_official_label text not null default '',
  ce_required boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
